// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6DpPIM6sH3uvTUFGXvXLaQYuFV98DNmQ',
    appId: '1:453462497977:web:fd0bce538018c725c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    authDomain: 'fir-loginsignup-6cdbe.firebaseapp.com',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbzcqTqxmGyVFxfS6e9heoQPpWrbVo0to',
    appId: '1:453462497977:android:6872ad268f365444c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAr2mDzcF5LZMJGdE5spJ1QVFEygO65po',
    appId: '1:453462497977:ios:134c0c30ce4dbc80c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
    androidClientId: '453462497977-me8j0ncfsrk2jsgebt223grpbfeecc67.apps.googleusercontent.com',
    iosClientId: '453462497977-t4tecquaao7gjbnbq56ccvqgono8tedo.apps.googleusercontent.com',
    iosBundleId: 'com.example.clipper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAr2mDzcF5LZMJGdE5spJ1QVFEygO65po',
    appId: '1:453462497977:ios:134c0c30ce4dbc80c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
    androidClientId: '453462497977-me8j0ncfsrk2jsgebt223grpbfeecc67.apps.googleusercontent.com',
    iosClientId: '453462497977-t4tecquaao7gjbnbq56ccvqgono8tedo.apps.googleusercontent.com',
    iosBundleId: 'com.example.clipper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6DpPIM6sH3uvTUFGXvXLaQYuFV98DNmQ',
    appId: '1:453462497977:web:98075e684a4a0988c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    authDomain: 'fir-loginsignup-6cdbe.firebaseapp.com',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
  );
}
